name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Get latest commit sha
        id: commit_sha_id
        run: | 
            tagcommitnumber=`git rev-parse --short HEAD`
            echo "COMMIT_SHA=$tagcommitnumber" >> $GITHUB_OUTPUT

      - name: Replace SQL Host URL
        uses: sherwin-williams-co/gha-find-replace@main
        with:
          find: "@MSQLSERVER@"
          replace: ${{ secrets.NP_MYSQL_SERVER_HOST }}
          include: Dockerfile

      - name: Replace SQL DB User
        uses: sherwin-williams-co/gha-find-replace@main
        with:
          find: "@DBUSER@"
          replace: ${{ secrets.NP_MYSQL_USER}}
          include: Dockerfile

      - name: Replace SQL DB Name
        uses: sherwin-williams-co/gha-find-replace@main
        with:
          find: "@DATABASENAME@"
          replace: ${{ secrets.NP_MYSQL_DATABASE_NAME}}
          include: Dockerfile

      - name: Build, push and tag container image
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          push: false
          context: .
          

